export const ROUTE_SIGNIN = 'SignIn'
export const ROUTE_RESET_PASSWORD = 'ResetPassword'
export const ROUTE_SIGNUP_LINK = 'Link'
export const ROUTE_SIGNIN_CONFIRM = 'Confirm'
export const ROUTE_USER_AGREEMENT = 'UserAgreement'
export const ROUTE_SIGNUP_VISITOR = 'Visitor'
export const ROUTE_NEW_PASSWORD = 'NewPassword'
export const ROUTE_SIGNUP = 'SignUp'
export const ROUTE_SIGNOUT = 'SignOut'
export const ROUTE_DASHBOARD = 'Dashboard'
export const ROUTE_USERS = 'Users'
export const ROUTE_USER = 'User'
export const ROUTE_COMPANY = 'Company'
export const ROUTE_BILLING = 'Billing'
export const ROUTE_WORKPLACE_READINESS = 'WorkplaceReadiness'
export const ROUTE_REPORTING = 'Reporting'
export const ROUTE_ENTRY_LIST = 'EntryList'
export const ROUTE_NOTIFICATIONS = 'Notifications'
export const ROUTE_MYACCOUNT = 'MyAccount'
export const ROUTE_COMPANIES = 'Companies'
export const ROUTE_ALLUSERS = 'AllUsers'
export const ROUTE_PUBLIC_READINESS = 'PublicReadiness'
export const ROUTE_ENTRY_SCAN = 'EntryScan'
export const ROUTE_VERIFIED_WORKFORCE = 'VerifiedWorkforce'
export const ROUTE_SURVEY_FORM = 'SurveyForm'
export const ROUTE_NOT_ALLOWED = 'NotAllowed'
export const ROUTE_SESSION_EXPIRED = 'SessionExpired'
export const ROUTE_DEBUG = 'Debug'
export const ROUTE_TOS = 'TermsOfService'
export const ROUTE_PRIVATEPOLICY = 'PrivatePolicy'

export const ROLE_SUPERUSER = 'superuser'
export const ROLE_COMPANY_SUPER_ADMIN = 'company_super_admin'
export const ROLE_COMPANY_ADMIN = 'company_admin'
export const ROLE_COMPANY_ENTRY = 'company_entry'
export const ROLE_COMPANY_BILLING = 'company_billing'
export const ROLE_DEPARTMENT_ADMIN = 'department_admin'
export const ROLE_DEPARTMENT_ENTRY = 'department_entry'
export const ROLE_COMPANY_USER = 'company_user'
export const ROLE_GENERAL_USER = 'general_user'

export const EVENT_CAPTURE_WORK = 'capture_work'
export const EVENT_CAPTURE_PUBLIC = 'capture_public'
export const EVENT_SEND = 'send'
export const EVENT_ENTRY = 'entry'
export const EVENT_SICK_DAY = 'sickday'
export const EVENT_WORK_FROM_HOME = 'wfh'
export const EVENT_QUARANTINE = 'quarantine'
export const EVENT_RESPONSE = 'response'
export const EVENT_COMMUNICATION = 'communication'
export const EVENT_TEST = 'test'
export const EVENT_VACCINE = 'vaccine'

export const TEST_TYPE_ANTIGEN = 'ANTIGEN'
export const TEST_TYPE_ANTIBODY = 'ANTIBODY'
export const TEST_TYPE_MOLECULAR = 'MOLECULAR'

export const SCENARIO_MFA_SIGNUP = 'signup'
export const SCENARIO_MFA_LOGIN = 'login'
export const SCENARIO_MFA_RESET = 'reset'
export const SCENARIO_MFA_NEW_PASSWORD = 'newpass'

export const ENV_PRODUCTION = 'production'

export const READINESS_FAILED = 'failed'
export const READINESS_PASSED = 'passed'

export const TEMPORARY_PASSWORD = 'TempoR@ry123'

export const CONSENT_USER_AGREEMENT = 'user_agreement'
export const CONSENT_HIPAA_VC = 'vc_hipaa'
